### ISSUE TITLE
20200504 DockerでReact開発環境構築

### ISSUE THREAD

**Issue by yukari710** [yukari710/til#12]
### 手順
1. Docker for Macをインストール
2. Dockerfile の設定
```
# コンテナのベースとなるDockerイメージを指定
FROM node:8.16.0-alpine
# コンテナ内の作業ディレクトリを指定
WORKDIR /usr/src/app
```
■Dockerfile とは
ベースとするDockerイメージに対して実行する内容を記述するもの。
Docker は Dockerfile から命令を読み込み、自動的にイメージを構築できる。

3. docker-compose.yaml の設定
```
version: '3'
services:
  node:
    build:
      context: .
    environment:
      - NODE_ENV=production
    volumes:
      - "./:/usr/src/app"
    command: sh -c "cd react-todo && npm start"
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    tty: true
```
■docker-compose.yaml とは
複数のコンテナで構成されるアプリケーションについて、Dockerイメージのビルドや各コンテナの起動・停止などをより簡単に行えるようにするツール。

version: docker-composeのバージョン
services: 構築するサービス情報
build: docker-compose.ymlがあるディレクトリに対するDockerfileのディレクトリを指定
environment: 環境変数を追加
volumes: ローカルのディレクトリがマウントする作業ディレクトリを指定
command: コンテナ内で実行されるコマンド
working_dir: 作業ディレクトリを指定
ports: 外部に対して公開するポート番号
tty: コンテナ起動を継続するかどうか指定

4. プロジェクトのディレクトリに移動し、Dockerコンテナをビルド
```
$ cd /プロジェクトディレクトリまでのパス
$ docker-compose build
```
イメージが作成できていることを確認。
`$ docker images`

5. create-react-app を実行
`$ docker-compose run --rm node sh -c "npm i -g create-react-app && create-react-app react-todo"`

プロジェクト配下に create-react-app ディレクトリが作成されていることを確認。(ls)

6. Docker コンテナを起動
`$ docker-compose run --rm --service-ports node`

コンテナが起動していることを確認。
`$ docker-compose ps`

7. React が起動したことを確認
※ React の start コマンドは docker-compose.yaml 内に記載しているため自動で実行される

起動に成功した場合、下記のメッセージが表示される。
```
Compiled successfully!

You can now view react-todo in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://172.19.0.2:3000

Note that the development build is not optimized.
To create a production build, use yarn build.
```

http://localhost:3000 にアクセスできることを確認。
